name: Auto-Version

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Run Test
        with:
          cmd: test

  version:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Configure committer
        run: |
          git config --local user.name "${{ secrets.COMMITTER_NAME }}"
          git config --local user.email "${{ secrets.COMMITTER_EMAIL }}"
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Bump version
        with:
          cmd: release
      - name: Publish
        run: |
          git push --follow-tags origin main
