name: Auto-Version

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Run Test
        with:
          cmd: test

  version:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Configure GPG Key
        run: |
          mkdir -p ~/.gnupg/
          printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
          gpg --import ~/.gnupg/private.key
        env:
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      - name: Configure committer
        run: |
          git config --local gpg.program $(which gpg)
          git config --local user.name "${{ secrets.COMMITTER_NAME }}"
          git config --local user.email "${{ secrets.COMMITTER_EMAIL }}"
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Bump version
        with:
          cmd: release
      - name: Publish
        run: |
          git push --follow-tags origin main
