name: Auto-Version

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Run Test
        with:
          cmd: test

  version:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Configure GPG Key
        run: gpg -v --import <(echo "$GPG_PRIVATE_KEY")
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Configure committer
        run: |
          git config --local gpg.program $(which gpg)
          git config --local user.name "${{ secrets.COMMITTER_NAME }}"
          git config --local user.email "${{ secrets.COMMITTER_EMAIL }}"
      - name: Bump version and publish
        run: git pull && yarn install && yarn release && git push --follow-tags origin main
