name: Auto-Version

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Run Test
        with:
          cmd: test

  version:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Debug GPG
        run: ls -la .gnupg
      - name: Import GPG
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_push_gpgsign: true
          git_tag_gpgsign: true
          git_committer_name: ${{ secrets.COMMITTER_NAME }}
          git_committer_email: ${{ secrets.COMMITTER_EMAIL }}
      - name: Configure committer
        run: |
          git config --local gpg.program $(which gpg2)
          git config --local user.name "${{ secrets.COMMITTER_NAME }}"
          git config --local user.email "${{ secrets.COMMITTER_EMAIL }}"
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Bump version
        with:
          cmd: release
      - name: Publish
        run: |
          git push --follow-tags origin main
