name: Auto-Version

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test New Release
    runs-on: self-hosted
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Run Test
        with:
          cmd: test

  version:
    name: Auto-Version
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          token: ${{ secrets.AUTOVERSION_TOKEN }}
          fetch-depth: 0
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Run Test
        with:
          cmd: test
      - uses: borales/actions-yarn@v2.3.0
        name: Bump version
        with:
          cmd: release
      - name: Publish
        run: git push --follow-tags origin main
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
