name: Main

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Run Test
        with:
          cmd: test

  version:
    name: Version Bump
    runs-on: self-hosted
    needs: [test]
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_PASSWORD }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: true
          git_committer_name: ${{ COMMITTER_NAME }}
          git_committer_email: ${{ COMMITTER_EMAIL }}
      - uses: borales/actions-yarn@v2.3.0
        name: Bump version
        with:
          cmd: release
      - name: Publish
        run: git push --follow-tags origin main

  build:
    name: Build Image
    runs-on: self-hosted
    needs: [test]
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - name: Get package version
        uses: martinbeentjes/npm-get-version-action@master
        id: package_version
      - name: Set image tag
        id: tag
        run: |
          echo "::set-output name=bare::${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}"
          echo "::set-output name=version::${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:${{ steps.package_version.outputs.current-version }}"
          echo "::set-output name=latest::${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:latest"
      - uses: docker/login-action@v1
        name: Login to docker registry
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: docker build -t ${{ steps.tag.outputs.latest }} -t ${{ steps.tag.outputs.version }} .
      - name: Push image
        run: docker push ${{ steps.tag.outputs.bare }}
