name: Main

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          token: ${{ secrets.AUTOVERSION_TOKEN }}
          fetch-depth: 0
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Run Test
        with:
          cmd: test

  version:
    name: Version Bump
    runs-on: self-hosted
    needs: [test]
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - name: Bump and Publish
        run: |
          git config --local user.signingkey "${{ secrets.GHA_DEPLOY_KEY }}"
          git config --local commit.gpgsign true
          git config --local user.email "${{ secrets.COMMITTER_EMAIL }}"
          git config --local user.name "${{ secrets.COMMITTER_NAME }}"
          git remote set-url origin "https://${{secrets.COMMITTER_NAME}}:${{secrets.AUTOVERSION_TOKEN}}@github.com/$GITHUB_REPOSITORY"
          yarn release
          git push --follow-tags origin main
